# Generated by Django 4.1.3 on 2022-11-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Sub-Категория', 'verbose_name_plural': 'Sub-Категории'},
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Sub-Категория'),
        ),
    ]
