# Generated by Django 4.1.3 on 2022-11-19 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_subcategory_options_alter_subcategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='material',
            field=models.CharField(max_length=50),
        ),
    ]
