# Generated by Django 4.1.3 on 2022-11-19 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_material_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='title',
            field=models.CharField(max_length=150, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.SlugField(max_length=160, null=True, unique=True),
        ),
    ]
