# Generated by Django 4.1.3 on 2022-11-19 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_productshots_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='poster',
            field=models.ImageField(null=True, upload_to='product/', verbose_name='Постер'),
        ),
    ]
