# Generated by Django 4.1.3 on 2022-11-21 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_product_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='category',
        ),
    ]
