# Generated by Django 4.1.3 on 2022-11-22 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_productmaterial_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='capacity',
            field=models.IntegerField(null=True, verbose_name='Вес'),
        ),
    ]
