# Generated by Django 4.1.3 on 2022-11-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_product_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productshots',
            name='image',
            field=models.ImageField(null=True, upload_to='product_shots/', verbose_name='Изоброжение_540x600'),
        ),
    ]
