# Generated by Django 4.1.3 on 2022-11-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_productshots_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productshots',
            old_name='image',
            new_name='image3',
        ),
        migrations.AddField(
            model_name='productshots',
            name='image1',
            field=models.ImageField(null=True, upload_to='product_shots/', verbose_name='Изоброжение_150x160'),
        ),
        migrations.AddField(
            model_name='productshots',
            name='image2',
            field=models.ImageField(null=True, upload_to='product_shots/', verbose_name='Изоброжение_810x900'),
        ),
    ]
