# Generated by Django 4.1.3 on 2022-11-23 15:19

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_rename_image_productshots_image3_productshots_image1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productshots',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='productshots',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='productshots',
            name='image3',
        ),
        migrations.AddField(
            model_name='productshots',
            name='image_big',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, scale=0.5, size=[540, 600], upload_to='product_shots/'),
        ),
        migrations.AddField(
            model_name='productshots',
            name='image_small',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, scale=0.5, size=[150, 160], upload_to='product_shots/'),
        ),
        migrations.AddField(
            model_name='productshots',
            name='image_zoom',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, scale=0.5, size=[810, 900], upload_to='product_shots/'),
        ),
    ]
