# Generated by Django 4.1.3 on 2022-11-23 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_remove_productshots_image1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productshots',
            old_name='image_big',
            new_name='imagebig',
        ),
        migrations.RenameField(
            model_name='productshots',
            old_name='image_small',
            new_name='imagesmall',
        ),
        migrations.RenameField(
            model_name='productshots',
            old_name='image_zoom',
            new_name='imagezoom',
        ),
    ]
