# Generated by Django 4.1.3 on 2022-11-25 13:10

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_rename_image_big_productshots_imagebig_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productshots',
            name='imagebig',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, scale=0.5, size=[1920, 1080], upload_to='product_shots/', verbose_name=[540, 600]),
        ),
        migrations.AlterField(
            model_name='productshots',
            name='imagesmall',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, scale=0.5, size=[1920, 1080], upload_to='product_shots/', verbose_name=[150, 160]),
        ),
        migrations.AlterField(
            model_name='productshots',
            name='imagezoom',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, scale=0.5, size=[1920, 1080], upload_to='product_shots/', verbose_name=[810, 900]),
        ),
    ]
