# Generated by Django 4.1.3 on 2022-11-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_productshots_imagebig_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productshots',
            name='imagebig',
        ),
        migrations.RemoveField(
            model_name='productshots',
            name='imagesmall',
        ),
        migrations.RemoveField(
            model_name='productshots',
            name='imagezoom',
        ),
        migrations.AddField(
            model_name='productshots',
            name='imageBig',
            field=models.ImageField(null=True, upload_to='product_shots/', verbose_name='Фото 540X600'),
        ),
        migrations.AddField(
            model_name='productshots',
            name='imageSmall',
            field=models.ImageField(null=True, upload_to='product_shots/', verbose_name='Фото 150X160'),
        ),
        migrations.AddField(
            model_name='productshots',
            name='imageZoom',
            field=models.ImageField(null=True, upload_to='product_shots/', verbose_name='Фото 810X900'),
        ),
    ]
