# Generated by Django 4.1.3 on 2022-11-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_alter_productshots_imagebig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slogan',
            field=models.CharField(max_length=200, null=True, verbose_name='Слоган'),
        ),
    ]
