# Generated by Django 4.1.3 on 2022-12-08 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_product_sale_alter_product_stock_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='country',
            new_name='state',
        ),
    ]
