# Generated by Django 4.1.3 on 2022-12-08 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_rename_country_shippingaddress_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cartPoster',
            field=models.ImageField(null=True, upload_to='product/', verbose_name='ПостерКорзинки'),
        ),
    ]
